In [1]:
import backtrader as bt
import pandas as pd
import datetime
import random
from StrategyLong import *
from StrategyShort import *

In [2]:
df = pd.read_csv('exportSignal.csv')
df.index = pd.to_datetime(df['time'], unit='s')
df = df[['open', 'high', 'low', 'close']].rename(
    columns={"open": "Open", "high": "High", "low": "Low", "close": "Close"})
data = bt.feeds.PandasData(dataname=df, volume=None, openinterest=None)

In [3]:
capital = 100000.0
if __name__ == '__main__':
    testpara = {
        'profit': 0,
        'fastlen': 60,
        'slowlen': 171,
        'signallen': 2,
        'close_fastlen': 9,
        'close_slowlen': 20,
        'close_signallen': 2,
        'topfilter': 152,
        'botfilter': 97,
        'stop_loss': 1000,
        'percent': 0.3
    }
    use_Percent = False
    use_Margin = True
    cerebro = bt.Cerebro(stdstats=False)
    cerebro.broker.setcash(capital)
    cerebro.resampledata(data,
                         timeframe=bt.TimeFrame.Minutes,
                         compression=60)
    cerebro.addanalyzer(bt.analyzers.PyFolio, _name='PF')
    cerebro.addobserver(bt.observers.Value)
    cerebro.addobserver(bt.observers.Trades)
    cerebro.addobserver(bt.observers.BuySell)
    cerebro.addobserver(bt.observers.DrawDown)

    cerebro.addstrategy(StShort, printlog=True, percent=testpara['percent'], stop_loss=testpara['stop_loss'], fastlen=testpara['fastlen'], slowlen=testpara['slowlen'], signallen=testpara['signallen'],
                        close_fastlen=testpara['close_fastlen'], close_slowlen=testpara['close_slowlen'], close_signallen=testpara['close_signallen'], topfilter=testpara['topfilter'], botfilter=testpara['botfilter'], useMargin=use_Margin, usePercent=use_Percent)
    if use_Margin:
        cerebro.broker.setcommission(margin=testpara['stop_loss'])

    print('Starting Portfolio Value: %.2f' % cerebro.broker.getvalue())
    result = cerebro.run()
    print('Final Portfolio: %.2f%%' %
          (cerebro.broker.getvalue() * 100 / capital))
    # print("Return:", result[0].analyzers.PF.get_analysis())
    pyfoliozer = result[0].analyzers.getbyname('PF')
    returns, positions, transactions, gross_lev = pyfoliozer.get_pf_items()
    import pyfolio as pf
    pf.create_full_tear_sheet(
        returns,
        positions=positions,
        transactions=transactions,
        live_start_date='2014-02-13',  # This date is sample specific
        round_trips=True)

    # cerebro.plot(volume=False, cash=False)
    # output = pd.DataFrame(final_results_list,
    #                       columns=['close_fastlen', 'close_slowlen', 'profit'])
    # output = output.sort_values(by=['profit'], ascending=False)
    # print("close_fastlen:",
    #       output.at[0, 'close_fastlen'], "close_slowlen:", output.at[
    #           0, 'close_slowlen'], "profit:{:.2%}".format(output.at[0, 'profit']))
    # output.to_csv("output.csv")

Starting Portfolio Value: 100000.00
2014-02-13, Sell CREATE, 22203.30
2014-02-13, SELL EXECUTED, Price: 22204.40, Cost: 1000.00, Cash: 98939.50, Position:-1
2014-03-21, Close CREATE, 21467.80
2014-03-24, Close EXECUTED, Price: 21657.50, Cost: 1000.00, Cash: 100546.90, Position:0
2014-03-24, OPERATION PROFIT, GROSS 546.90, NET 546.90
2014-07-30, Sell CREATE, 24835.60
2014-07-30, SELL EXECUTED, Price: 24850.30, Cost: 1000.00, Cash: 99723.90, Position:-1
2014-10-06, Close CREATE, 23171.10
2014-10-06, Close EXECUTED, Price: 23171.00, Cost: 1000.00, Cash: 102226.20, Position:0
2014-10-06, OPERATION PROFIT, GROSS 1679.30, NET 1679.30
2014-10-30, Sell CREATE, 23752.60
2014-10-30, SELL EXECUTED, Price: 23751.30, Cost: 1000.00, Cash: 101270.20, Position:-1
2014-12-19, Close CREATE, 23141.70
2014-12-19, Close EXECUTED, Price: 23142.20, Cost: 1000.00, Cash: 102835.30, Position:0
2014-12-19, OPERATION PROFIT, GROSS 609.10, NET 609.10
2015-01-23, Sell CREATE, 24808.20
2015-01-23, SELL EXECUTED, Price: 24811.00, Cost: 1000.00, Cash: 101833.30, Position:-1
2015-03-16, Close CREATE, 23937.50
2015-03-16, Close EXECUTED, Price: 23935.70, Cost: 1000.00, Cash: 103710.60, Position:0
2015-03-16, OPERATION PROFIT, GROSS 875.30, NET 875.30
2015-04-09, Sell CREATE, 27084.20
2015-04-09, SELL EXECUTED, Price: 27082.40, Cost: 1000.00, Cash: 102840.20, Position:-1
2015-04-23, Order stop loss, Position:0
2015-04-23, OPERATION PROFIT, GROSS -1085.00, NET -1085.00
2015-04-27, Sell CREATE, 28431.80
2015-04-28, SELL EXECUTED, Price: 28448.20, Cost: 1000.00, Cash: 101773.50, Position:-1
2015-06-12, Close CREATE, 27230.20
2015-06-12, Close EXECUTED, Price: 27231.30, Cost: 1000.00, Cash: 103842.50, Position:0
2015-06-12, OPERATION PROFIT, GROSS 1216.90, NET 1216.90
2015-09-10, Sell CREATE, 21598.60
2015-09-10, SELL EXECUTED, Price: 21595.70, Cost: 1000.00, Cash: 102829.70, Position:-1
2015-10-02, Close CREATE, 21333.20
2015-10-02, Close EXECUTED, Price: 21334.00, Cost: 1000.00, Cash: 104104.20, Position:0
2015-10-02, OPERATION PROFIT, GROSS 261.70, NET 261.70
2015-10-05, Sell CREATE, 21800.10
2015-10-05, SELL EXECUTED, Price: 21800.30, Cost: 1000.00, Cash: 103110.30, Position:-1
2015-10-15, Order stop loss, Position:0
2015-10-15, OPERATION PROFIT, GROSS -1000.00, NET -1000.00
2016-03-03, Sell CREATE, 19934.40
2016-03-03, SELL EXECUTED, Price: 19933.80, Cost: 1000.00, Cash: 102183.80, Position:-1
2016-04-13, Order stop loss, Position:0
2016-04-13, OPERATION PROFIT, GROSS -1012.30, NET -1012.30
2016-04-14, Sell CREATE, 21332.60
2016-04-14, SELL EXECUTED, Price: 21331.00, Cost: 1000.00, Cash: 101093.30, Position:-1
2016-05-17, Close CREATE, 20016.20
2016-05-17, Close EXECUTED, Price: 20015.20, Cost: 1000.00, Cash: 103407.70, Position:0
2016-05-17, OPERATION PROFIT, GROSS 1315.80, NET 1315.80
2016-07-04, Sell CREATE, 21055.42
2016-07-04, SELL EXECUTED, Price: 21056.30, Cost: 1000.00, Cash: 102401.10, Position:-1
2016-07-21, Order stop loss, Position:0
2016-07-21, OPERATION PROFIT, GROSS -1000.00, NET -1000.00
2016-09-05, Sell CREATE, 23614.37
2016-09-05, SELL EXECUTED, Price: 23611.55, Cost: 1000.00, Cash: 101351.83, Position:-1
2016-11-01, Close CREATE, 23241.33
2016-11-01, Close EXECUTED, Price: 23241.22, Cost: 1000.00, Cash: 102778.03, Position:0
2016-11-01, OPERATION PROFIT, GROSS 370.33, NET 370.33
2017-07-13, Sell CREATE, 26299.60
2017-07-13, SELL EXECUTED, Price: 26300.03, Cost: 1000.00, Cash: 101762.62, Position:-1
2017-07-31, Order stop loss, Position:0
2017-07-31, OPERATION PROFIT, GROSS -1003.98, NET -1003.98
2017-10-04, Sell CREATE, 28344.64
2017-10-04, SELL EXECUTED, Price: 28345.30, Cost: 1000.00, Cash: 100759.72, Position:-1
2017-11-21, Order stop loss, Position:0
2017-11-21, OPERATION PROFIT, GROSS -1179.79, NET -1179.79
2017-11-22, Sell CREATE, 29968.78
2017-11-22, SELL EXECUTED, Price: 29964.18, Cost: 1000.00, Cash: 99500.67, Position:-1
2017-12-11, Close CREATE, 28874.57
2017-12-11, Close EXECUTED, Price: 28874.44, Cost: 1000.00, Cash: 101684.00, Position:0
2017-12-11, OPERATION PROFIT, GROSS 1089.74, NET 1089.74
2018-01-03, Sell CREATE, 30615.75
2018-01-03, SELL EXECUTED, Price: 30613.03, Cost: 1000.00, Cash: 100701.55, Position:-1
2018-01-15, Order stop loss, Position:0
2018-01-15, OPERATION PROFIT, GROSS -1063.41, NET -1063.41
2018-01-24, Sell CREATE, 32802.06
2018-01-24, SELL EXECUTED, Price: 32802.51, Cost: 1000.00, Cash: 99644.59, Position:-1
2018-02-14, Close CREATE, 30374.41
2018-02-14, Close EXECUTED, Price: 30373.83, Cost: 1000.00, Cash: 103049.27, Position:0
2018-02-14, OPERATION PROFIT, GROSS 2428.68, NET 2428.68
2018-02-20, Sell CREATE, 31047.38
2018-02-20, SELL EXECUTED, Price: 31046.91, Cost: 1000.00, Cash: 102080.19, Position:-1
2018-03-01, Close CREATE, 31044.25
2018-03-02, Close EXECUTED, Price: 30611.10, Cost: 1000.00, Cash: 103485.08, Position:0
2018-03-02, OPERATION PROFIT, GROSS 435.81, NET 435.81
2018-03-13, Sell CREATE, 31527.48
2018-03-13, SELL EXECUTED, Price: 31530.99, Cost: 1000.00, Cash: 102508.31, Position:-1
2018-04-09, Close CREATE, 30208.99
2018-04-09, Close EXECUTED, Price: 30208.72, Cost: 1000.00, Cash: 104807.35, Position:0
2018-04-09, OPERATION PROFIT, GROSS 1322.27, NET 1322.27
2018-04-11, Sell CREATE, 30867.30
2018-04-11, SELL EXECUTED, Price: 30869.68, Cost: 1000.00, Cash: 103785.74, Position:-1
2018-04-19, Close CREATE, 30578.02
2018-04-19, Close EXECUTED, Price: 30571.77, Cost: 1000.00, Cash: 105105.26, Position:0
2018-04-19, OPERATION PROFIT, GROSS 297.91, NET 297.91
2018-05-11, Sell CREATE, 31144.66
2018-05-11, SELL EXECUTED, Price: 31145.74, Cost: 1000.00, Cash: 104128.94, Position:-1
2018-06-29, Close CREATE, 28821.90
2018-06-29, Close EXECUTED, Price: 28828.56, Cost: 1000.00, Cash: 107422.44, Position:0
2018-06-29, OPERATION PROFIT, GROSS 2317.18, NET 2317.18
2018-07-25, Sell CREATE, 28874.82
2018-07-25, SELL EXECUTED, Price: 28875.84, Cost: 1000.00, Cash: 106354.64, Position:-1
2018-08-07, Close CREATE, 28087.02
2018-08-07, Close EXECUTED, Price: 28081.99, Cost: 1000.00, Cash: 108216.29, Position:0
2018-08-07, OPERATION PROFIT, GROSS 793.85, NET 793.85
2018-08-09, Sell CREATE, 28592.31
2018-08-09, SELL EXECUTED, Price: 28595.71, Cost: 1000.00, Cash: 107204.70, Position:-1
2018-08-20, Close CREATE, 27457.66
2018-08-20, Close EXECUTED, Price: 27457.49, Cost: 1000.00, Cash: 109354.51, Position:0
2018-08-20, OPERATION PROFIT, GROSS 1138.22, NET 1138.22
2018-08-28, Sell CREATE, 28340.20
2018-08-28, SELL EXECUTED, Price: 28339.35, Cost: 1000.00, Cash: 108372.42, Position:-1
2018-09-13, Close CREATE, 26740.56
2018-09-13, Close EXECUTED, Price: 26738.31, Cost: 1000.00, Cash: 110955.55, Position:0
2018-09-13, OPERATION PROFIT, GROSS 1601.04, NET 1601.04
2018-09-24, Sell CREATE, 27602.91
2018-09-24, SELL EXECUTED, Price: 27604.74, Cost: 1000.00, Cash: 109949.87, Position:-1
2018-10-19, Close CREATE, 25556.70
2018-10-19, Close EXECUTED, Price: 25553.78, Cost: 1000.00, Cash: 113006.51, Position:0
2018-10-19, OPERATION PROFIT, GROSS 2050.96, NET 2050.96
2018-10-23, Sell CREATE, 25839.20
2018-10-23, SELL EXECUTED, Price: 25840.59, Cost: 1000.00, Cash: 112266.19, Position:-1
2018-10-24, Close CREATE, 25575.80
2018-10-24, Close EXECUTED, Price: 25578.99, Cost: 1000.00, Cash: 113268.11, Position:0
2018-10-24, OPERATION PROFIT, GROSS 261.60, NET 261.60
2018-11-05, Sell CREATE, 26053.88
2018-11-05, SELL EXECUTED, Price: 26050.39, Cost: 1000.00, Cash: 112450.52, Position:-1
2018-11-13, Close CREATE, 25792.87
2018-11-14, Close EXECUTED, Price: 25874.36, Cost: 1000.00, Cash: 113444.14, Position:0
2018-11-14, OPERATION PROFIT, GROSS 176.03, NET 176.03
2018-12-04, Sell CREATE, 27071.93
2018-12-04, SELL EXECUTED, Price: 27075.92, Cost: 1000.00, Cash: 112424.11, Position:-1
2018-12-27, Close CREATE, 25806.92
2018-12-27, Close EXECUTED, Price: 25803.44, Cost: 1000.00, Cash: 114716.62, Position:0
2018-12-27, OPERATION PROFIT, GROSS 1272.48, NET 1272.48
2019-01-09, Sell CREATE, 26438.45
2019-01-09, SELL EXECUTED, Price: 26438.84, Cost: 1000.00, Cash: 113693.14, Position:-1
2019-01-25, Order stop loss, Position:0
2019-01-25, OPERATION PROFIT, GROSS -1000.00, NET -1000.00
2019-04-01, Sell CREATE, 29562.02
2019-04-02, SELL EXECUTED, Price: 29736.99, Cost: 1000.00, Cash: 112827.57, Position:-1

2019-05-28, Close CREATE, 27370.70
2019-05-28, Close EXECUTED, Price: 27368.87, Cost: 1000.00, Cash: 116084.74, Position:0
2019-05-28, OPERATION PROFIT, GROSS 2368.12, NET 2368.12
2019-06-11, Sell CREATE, 27813.69
2019-06-11, SELL EXECUTED, Price: 27817.09, Cost: 1000.00, Cash: 115112.49, Position:-1
2019-06-13, Close CREATE, 27096.99
2019-06-13, Close EXECUTED, Price: 27097.60, Cost: 1000.00, Cash: 116804.23, Position:0
2019-06-13, OPERATION PROFIT, GROSS 719.49, NET 719.49
2019-06-20, Sell CREATE, 28426.94
2019-06-20, SELL EXECUTED, Price: 28425.49, Cost: 1000.00, Cash: 115771.45, Position:-1
2019-08-15, Close CREATE, 25453.65
2019-08-15, Close EXECUTED, Price: 25454.76, Cost: 1000.00, Cash: 119774.96, Position:0
2019-08-15, OPERATION PROFIT, GROSS 2970.73, NET 2970.73
2019-08-20, Sell CREATE, 26290.14
2019-08-20, SELL EXECUTED, Price: 26289.54, Cost: 1000.00, Cash: 118786.95, Position:-1
2019-08-27, Close CREATE, 25739.33
2019-08-27, Close EXECUTED, Price: 25739.81, Cost: 1000.00, Cash: 120324.69, Position:0
2019-08-27, OPERATION PROFIT, GROSS 549.73, NET 549.73
2019-09-05, Sell CREATE, 26291.17
2019-09-05, SELL EXECUTED, Price: 26291.10, Cost: 1000.00, Cash: 119236.53, Position:-1
2019-09-13, Order stop loss, Position:0
2019-09-13, OPERATION PROFIT, GROSS -1005.46, NET -1005.46
2019-10-14, Sell CREATE, 26557.26
2019-10-14, SELL EXECUTED, Price: 26552.19, Cost: 1000.00, Cash: 118328.36, Position:-1
2019-11-05, Order stop loss, Position:0
2019-11-05, OPERATION PROFIT, GROSS -1000.00, NET -1000.00
2019-11-05, Sell CREATE, 27693.03
2019-11-05, SELL EXECUTED, Price: 27696.43, Cost: 1000.00, Cash: 117411.14, Position:-1
2019-12-06, Close CREATE, 26435.68
2019-12-06, Close EXECUTED, Price: 26432.73, Cost: 1000.00, Cash: 119582.93, Position:0
2019-12-06, OPERATION PROFIT, GROSS 1263.70, NET 1263.70
2019-12-10, (Entry: 60\171\2)(Close: 9\20\2) Ending Value 119582.93
Final Portfolio: 119.58%

C:\Users\User\Anaconda3\lib\site-packages\pyfolio\pos.py:27: UserWarning: Module "zipline.assets" not found; mutltipliers will not be applied to position notionals.
  'Module "zipline.assets" not found; mutltipliers will not be applied' +
C:\Users\User\Anaconda3\lib\site-packages\empyrical\stats.py:711: RuntimeWarning: invalid value encountered in true_divide
  out=out,
C:\Users\User\Anaconda3\lib\site-packages\empyrical\stats.py:797: RuntimeWarning: invalid value encountered in true_divide
  np.divide(average_annual_return, annualized_downside_risk, out=out)
C:\Users\User\Anaconda3\lib\site-packages\empyrical\stats.py:1526: RuntimeWarning: invalid value encountered in double_scalars
  np.abs(np.percentile(returns, 5))

C:\Users\User\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:56: FutureWarning:
The current behaviour of 'Series.argmin' is deprecated, use 'idxmin'
instead.
The behavior of 'argmin' will be corrected to return the positional
minimum in the future. For now, use 'series.values.argmin' or
'np.argmin(np.array(values))' to get the position of the minimum
row.
  return getattr(obj, method)(*args, **kwds)

C:\Users\User\Anaconda3\lib\site-packages\matplotlib\axes\_base.py:3507: UserWarning: Attempting to set identical bottom==top results
in singular transformations; automatically expanding.
bottom=1.0, top=1.0
  self.set_ylim(upper, lower, auto=None)
C:\Users\User\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:56: FutureWarning:
The current behaviour of 'Series.argmin' is deprecated, use 'idxmin'
instead.
The behavior of 'argmin' will be corrected to return the positional
minimum in the future. For now, use 'series.values.argmin' or
'np.argmin(np.array(values))' to get the position of the minimum
row.
  return getattr(obj, method)(*args, **kwds)

C:\Users\User\Anaconda3\lib\site-packages\pandas\core\arrays\datetimes.py:1172: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  "will drop timezone information.", UserWarning)

C:\Users\User\Anaconda3\lib\site-packages\pyfolio\tears.py:779: UserWarning: Unable to generate turnover plot.
  warnings.warn('Unable to generate turnover plot.', UserWarning)
C:\Users\User\Anaconda3\lib\site-packages\pyfolio\round_trips.py:133: FutureWarning: Interpreting tuple 'by' as a list of keys, rather than a single key. Use 'by=[...]' instead of 'by=(...)'. In the future, a tuple will always mean a single key.
  grouped_price = (t.groupby(('block_dir',
C:\Users\User\Anaconda3\lib\site-packages\pyfolio\round_trips.py:137: FutureWarning: Interpreting tuple 'by' as a list of keys, rather than a single key. Use 'by=[...]' instead of 'by=(...)'. In the future, a tuple will always mean a single key.
  grouped_rest = t.groupby(('block_dir', 'block_time')).agg({
C:\Users\User\Anaconda3\lib\site-packages\pyfolio\round_trips.py:80: FutureWarning: using a dict on a Series for aggregation
is deprecated and will be removed in a future version
  .agg(stats_dict)
C:\Users\User\Anaconda3\lib\site-packages\pyfolio\round_trips.py:83: FutureWarning: Using 'rename_axis' to alter labels is deprecated. Use '.rename' instead
  axis='columns'))
C:\Users\User\Anaconda3\lib\site-packages\pyfolio\round_trips.py:86: FutureWarning: using a dict on a Series for aggregation
is deprecated and will be removed in a future version
  .agg(stats_dict)
C:\Users\User\Anaconda3\lib\site-packages\pyfolio\round_trips.py:90: FutureWarning: Using 'rename_axis' to alter labels is deprecated. Use '.rename' instead
  axis='columns'))
C:\Users\User\Anaconda3\lib\site-packages\pyfolio\round_trips.py:379: FutureWarning: using a dict on a Series for aggregation
is deprecated and will be removed in a future version
  round_trips.groupby('symbol')['returns'].agg(RETURN_STATS).T

C:\Users\User\Anaconda3\lib\site-packages\seaborn\distributions.py:198: RuntimeWarning: Mean of empty slice.
  line, = ax.plot(a.mean(), 0)
C:\Users\User\Anaconda3\lib\site-packages\numpy\core\_methods.py:85: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)